/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    infoBanner: IInfoBanner;
    rtBlock: IRichText;
    image: IImage;
    gutter: IGutter;
    gutterv2: IGutterV2;
    clipGutter: IClipGutter;
    button: IButtonBlock;
    blockColumnLayout: IBlockColumnLayout;
    flexboxLayout: IFlexboxLayout;
    calistoFeatureCard: ICalistoFeatureCard;
    discountCard: IDiscountCard;
    singleCard: ISingleCard;
    hoverCard: IHoverCard;
    richTextCard: IRichTextCard;
    cutoutCard: ICutoutCard;
    textUnderCard: ITextUnderCard;
    bentoGrid: BentoGrid;
    stickyContainers: IStickyContainers;
    accordion: IAccordion;
    carousel: ICarousel;
    marquee: IMarquee;
    flexItem: IFlexItem;
    wavyText: IWavyText;
    calistoLanding: ICalistoLanding;
    gradientBG: IGradientBG;
    mediumHero: IMediumHero;
    scrollGrowLanding: IScrollGrowLanding;
    heroCutout: IHeroCutout;
    imageHeader: IImageHeader;
    floatingHeader: IFloatingHeader;
    midFloatHeader: IMidFloadHeader;
    richTextFooter: IRichTextFooter;
    footerDesign2: IFooterDesign2;
    googleMapFooter: IGoogleMapFooter;
    pill: IPillRTBlock;
    buttonRT: IImageRTBlock;
    svgText: ISVGText;
    listMarkerIcon: ILexicalMarkerIcon;
    divider: IDivider;
    lexIcon: IRTIcon;
    lexImg: ILexicalImage;
    contactForm: IContactFormBlock;
    emboldenEpubConverter: EmboldenEpubConverterI;
    googlemaps: IGoogleMaps;
    textImageSplit: ITextImageSplit;
    tgkLandingHome: ITGKLandingHome;
    tgkCard1: ITGKCard1;
    tgkCard2: ITGKCard2;
    tgkDoilyCard: ITGKDoilyCard;
    tgkAccordion: ITGKAccordion;
    tgkGridIcons: ITGKGridIcons;
  };
  collections: {
    users: User;
    assets: Asset;
    pages: Page;
    tenants: Tenant;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    tenants: {
      pages: 'pages';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'el') | ('en' | 'el')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'el';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IInfoBanner".
 */
export interface IInfoBanner {
  richText?: IRichTextField;
  link?: IButton;
  style?: {
    background?: string | null;
    height?: string | null;
    padding?: string | null;
    border?: string | null;
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'infoBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IRichTextField".
 */
export interface IRichTextField {
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  img?: IImageField;
  style?: {
    background?: string | null;
    padding?: string | null;
    maxWidth?: string | null;
    height?: string | null;
    minHeight?: string | null;
    marker?: string | null;
    textWrap?: string | null;
    border?: string | null;
    borderRadius?: string | null;
  };
  mobileStyle?: {
    textAlign?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IImageField".
 */
export interface IImageField {
  url?: (number | null) | Asset;
  alt?: string | null;
  ignoreSizes?: boolean | null;
  style?: {
    background?: string | null;
    mixBlendMode?: string | null;
    opacity?: number | null;
    height?: string | null;
    width?: string | null;
    objectFit?: string | null;
    objectPosition?: string | null;
    padding?: string | null;
    borderRadius?: string | null;
    sizes?: string | null;
  };
  mobileStyle?: {
    padding?: string | null;
  };
  arr?:
    | {
        s?: IStickerField;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    placeholder?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IStickerField".
 */
export interface IStickerField {
  url?: (number | null) | Asset;
  style?: {
    top?: string | null;
    left?: string | null;
    right?: string | null;
    bottom?: string | null;
    height?: string | null;
    width?: string | null;
    objectFit?: string | null;
  };
  mobileStyle?: {
    top?: string | null;
    left?: string | null;
    right?: string | null;
    bottom?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IButton".
 */
export interface IButton {
  type?: ('reference' | 'custom') | null;
  reference?: {
    relationTo: 'pages';
    value: number | Page;
  } | null;
  url?: string | null;
  display?: {
    variant?: ('default' | 'secondary' | 'outline' | 'ghost' | 'link') | null;
    size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    text?: string | null;
    includeIcon?: boolean | null;
    icon?: IIcon;
  };
  style?: {
    padding?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title?: string | null;
  slug?: string | null;
  'tenant-domain'?: string | null;
  hero?:
    | (
        | IGradientBG
        | IMediumHero
        | ICalistoLanding
        | IScrollGrowLanding
        | IHeroCutout
        | IBlockColumnLayout
        | ITextImageSplit
        | ITGKLandingHome
      )[]
    | null;
  layout?:
    | (
        | IInfoBanner
        | IButtonBlock
        | IRichText
        | IImage
        | IGutter
        | IGutterV2
        | IClipGutter
        | IStickyContainers
        | BentoGrid
        | IAccordion
        | ICarousel
        | IFlexItem
        | IWavyText
        | IBlockColumnLayout
        | IFlexboxLayout
        | ICalistoFeatureCard
        | IDiscountCard
        | ISingleCard
        | IHoverCard
        | ICutoutCard
        | IRichTextCard
        | ITextUnderCard
        | IGradientBG
        | IMediumHero
        | IScrollGrowLanding
        | IHeroCutout
        | IContactFormBlock
        | IMarquee
        | EmboldenEpubConverterI
        | ITextImageSplit
        | ITGKLandingHome
        | ITGKCard1
        | ITGKCard2
        | ITGKDoilyCard
        | ITGKAccordion
        | ITGKGridIcons
      )[]
    | null;
  meta?: ISEO;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Used for domain-based tenant handling
   */
  domain?: string | null;
  pages?: {
    docs?: (number | Page)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  nav?: INavigation;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "INavigation".
 */
export interface INavigation {
  header?: (IImageHeader | IFloatingHeader | IMidFloadHeader)[] | null;
  footer?: (IRichTextFooter | IFooterDesign2 | IGoogleMapFooter)[] | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IImageHeader".
 */
export interface IImageHeader {
  image?: IImageField;
  nav?:
    | {
        link?: IButton;
        id?: string | null;
      }[]
    | null;
  style?: {
    hasShadow?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageHeader';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IFloatingHeader".
 */
export interface IFloatingHeader {
  image?: IImageField;
  nav?:
    | {
        link?: IButton;
        id?: string | null;
      }[]
    | null;
  style?: {
    inset?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'floatingHeader';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IMidFloadHeader".
 */
export interface IMidFloadHeader {
  left?:
    | {
        nLink?: INestedLink;
        id?: string | null;
      }[]
    | null;
  image?: IImageField;
  right?:
    | {
        nLink?: INestedLink;
        id?: string | null;
      }[]
    | null;
  style?: {
    inset?: string | null;
    background?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'midFloatHeader';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "INestedLink".
 */
export interface INestedLink {
  name?: string | null;
  arr?:
    | {
        link?: IButton;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IRichTextFooter".
 */
export interface IRichTextFooter {
  image?: IImageField;
  richText?: IRichTextField;
  contact?: {
    q?: string | null;
    email?: string | null;
  };
  nav?:
    | {
        link?: IButton;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        link?: IButton;
        id?: string | null;
      }[]
    | null;
  style?: {
    background?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richTextFooter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IFooterDesign2".
 */
export interface IFooterDesign2 {
  columnOne?:
    | (
        | ITextUnderCard
        | ISingleCard
        | IAccordion
        | IHoverCard
        | IRichTextCard
        | ICutoutCard
        | IButtonBlock
        | IRichText
        | IImage
        | IStickyContainers
        | BentoGrid
        | IContactFormBlock
        | ICarousel
        | IFlexItem
        | IWavyText
        | EmboldenEpubConverterI
        | ITextImageSplit
        | ITGKCard1
        | ITGKCard2
        | ITGKDoilyCard
        | ITGKAccordion
        | ITGKGridIcons
        | IFlexboxLayout
      )[]
    | null;
  columnTwo?:
    | (
        | ITextUnderCard
        | ISingleCard
        | IAccordion
        | IHoverCard
        | IRichTextCard
        | ICutoutCard
        | IButtonBlock
        | IRichText
        | IImage
        | IStickyContainers
        | BentoGrid
        | IContactFormBlock
        | ICarousel
        | IFlexItem
        | IWavyText
        | EmboldenEpubConverterI
        | ITextImageSplit
        | ITGKCard1
        | ITGKCard2
        | ITGKDoilyCard
        | ITGKAccordion
        | ITGKGridIcons
        | IFlexboxLayout
      )[]
    | null;
  columnThree?:
    | (
        | ITextUnderCard
        | ISingleCard
        | IAccordion
        | IHoverCard
        | IRichTextCard
        | ICutoutCard
        | IButtonBlock
        | IRichText
        | IImage
        | IStickyContainers
        | BentoGrid
        | IContactFormBlock
        | ICarousel
        | IFlexItem
        | IWavyText
        | EmboldenEpubConverterI
        | ITextImageSplit
        | ITGKCard1
        | ITGKCard2
        | ITGKDoilyCard
        | ITGKAccordion
        | ITGKGridIcons
        | IFlexboxLayout
      )[]
    | null;
  style?: {
    container?: boolean | null;
    background?: string | null;
    borderRadius?: string | null;
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
    alignY?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'footerDesign2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ITextUnderCard".
 */
export interface ITextUnderCard {
  image?: IImageField;
  richText?: IRichTextField;
  link?: (number | null) | Page;
  style?: {
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
    alignY?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'textUnderCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ISingleCard".
 */
export interface ISingleCard {
  image?: IImageField;
  richText?: IRichTextField;
  link?: (number | null) | Page;
  style?: {
    background?: string | null;
    width?: string | null;
    maxWidth?: string | null;
    border?: string | null;
    borderRadius?: string | null;
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
    alignY?: ('start' | 'center' | 'end' | 'stretch') | null;
    hasShadow?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'singleCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IAccordion".
 */
export interface IAccordion {
  icon?: IIcon;
  list?:
    | {
        title?: string | null;
        richText?: IRichTextField;
        id?: string | null;
      }[]
    | null;
  link?: IButton;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * Icon sets: https://icon-sets.iconify.design/
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IIcon".
 */
export interface IIcon {
  name?: string | null;
  size?: string | null;
  style?: {
    background?: string | null;
    color?: string | null;
    width?: string | null;
    height?: string | null;
    border?: string | null;
    borderRadius?: string | null;
    overflow?: string | null;
    string?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IHoverCard".
 */
export interface IHoverCard {
  image?: IImageField;
  title?: string | null;
  description?: string | null;
  style?: {
    background?: string | null;
    fontSize?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hoverCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IRichTextCard".
 */
export interface IRichTextCard {
  richText?: IRichTextField;
  link?: (number | null) | Page;
  image?: IImageField;
  style?: {
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
    alignY?: ('start' | 'center' | 'end' | 'stretch') | null;
    borderRadius?: string | null;
    background?: string | null;
    width?: string | null;
    maxWidth?: string | null;
    border?: string | null;
    hasShadow?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richTextCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ICutoutCard".
 */
export interface ICutoutCard {
  image?: IImageField;
  link?: IButton;
  style?: {
    padding?: string | null;
    width?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cutoutCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IButtonBlock".
 */
export interface IButtonBlock {
  link?: IButton;
  style?: {
    padding?: string | null;
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
    alignY?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IRichText".
 */
export interface IRichText {
  richText?: IRichTextField;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rtBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IImage".
 */
export interface IImage {
  image?: IImageField;
  style?: {
    height?: string | null;
    width?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IStickyContainers".
 */
export interface IStickyContainers {
  title?: string | null;
  list?:
    | {
        richText?: IRichTextField;
        image?: IImageField;
        id?: string | null;
      }[]
    | null;
  style?: {
    padding?: string | null;
    gap?: string | null;
    multiBg?: {
      /**
       * comma seperated eg #fff, #d2d2d2
       */
      bgs?: string | null;
      k?: number | null;
    };
    border?: string | null;
    borderRadius?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'stickyContainers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bentoGrid".
 */
export interface BentoGrid {
  grid?:
    | {
        content?: (IRichText | IImage)[] | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bentoGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IContactFormBlock".
 */
export interface IContactFormBlock {
  form?: (number | null) | Form;
  design?: ('oneLineEmail' | 'default') | null;
  style?: {
    width?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ICarousel".
 */
export interface ICarousel {
  items?:
    | (
        | IHoverCard
        | ITextUnderCard
        | IRichTextCard
        | ISingleCard
        | IRichText
        | IImage
        | IFlexItem
        | ITGKCard1
        | ITGKCard2
        | ITGKDoilyCard
      )[]
    | null;
  options?: {
    loop?: boolean | null;
  };
  style?: {
    background?: string | null;
    gap?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IFlexItem".
 */
export interface IFlexItem {
  list?:
    | {
        icon?: IIcon;
        richText?: IRichTextField;
        image?: IImageField;
        id?: string | null;
      }[]
    | null;
  style?: {
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
    alignY?: ('start' | 'center' | 'end' | 'stretch') | null;
    background?: string | null;
    flexDirection?: string | null;
    gap?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'flexItem';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ITGKCard1".
 */
export interface ITGKCard1 {
  title?: string | null;
  left?: boolean | null;
  style?: {
    background?: string | null;
    color?: string | null;
    height?: string | null;
    width?: string | null;
  };
  mobileStyles?: {
    height?: string | null;
    width?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'tgkCard1';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ITGKCard2".
 */
export interface ITGKCard2 {
  image?: IImageField;
  title?: string | null;
  style?: {
    background?: string | null;
    height?: string | null;
    border?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'tgkCard2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ITGKDoilyCard".
 */
export interface ITGKDoilyCard {
  bg?: IImageField;
  img?: IImageField;
  style?: {
    padding?: string | null;
    height?: string | null;
    width?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'tgkDoilyCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IWavyText".
 */
export interface IWavyText {
  text?: string | null;
  svg?: {
    clipPath?: string | null;
    path?: string | null;
    viewbox?: string | null;
    strokeColor?: string | null;
    strokeWidth?: string | null;
    color?: string | null;
    background?: string | null;
    fontSize?: string | null;
    wordSpacing?: string | null;
  };
  style?: {
    height?: string | null;
    width?: string | null;
    background?: string | null;
  };
  bgImage?: IImageField;
  id?: string | null;
  blockName?: string | null;
  blockType: 'wavyText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmboldenEpubConverterI".
 */
export interface EmboldenEpubConverterI {
  id?: string | null;
  blockName?: string | null;
  blockType: 'emboldenEpubConverter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ITextImageSplit".
 */
export interface ITextImageSplit {
  image?: IImageField;
  richText?: IRichTextField;
  left?: boolean | null;
  style?: {
    background?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'textImageSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ITGKAccordion".
 */
export interface ITGKAccordion {
  icon?: IIcon;
  list?:
    | {
        title?: string | null;
        richText?: IRichTextField;
        id?: string | null;
      }[]
    | null;
  style?: {
    background?: string | null;
    padding?: string | null;
    gap?: string | null;
    container?: boolean | null;
    width?: string | null;
  };
  btnStyle?: {
    padding?: string | null;
    background?: string | null;
    border?: string | null;
    borderRadius?: string | null;
  };
  dropStyle?: {
    padding?: string | null;
    background?: string | null;
    border?: string | null;
    borderRadius?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'tgkAccordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ITGKGridIcons".
 */
export interface ITGKGridIcons {
  arr?:
    | {
        icon?: IIcon;
        richText?: IRichTextField;
        id?: string | null;
      }[]
    | null;
  style?: {
    background?: string | null;
    padding?: string | null;
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
    alignY?: ('start' | 'center' | 'end' | 'stretch') | null;
    gap?: string | null;
    width?: string | null;
    container?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'tgkGridIcons';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IFlexboxLayout".
 */
export interface IFlexboxLayout {
  list?:
    | {
        block?:
          | (
              | ITextUnderCard
              | ISingleCard
              | IAccordion
              | IHoverCard
              | IRichTextCard
              | ICutoutCard
              | IButtonBlock
              | IRichText
              | IImage
              | IStickyContainers
              | BentoGrid
              | IContactFormBlock
              | ICarousel
              | IFlexItem
              | IWavyText
              | EmboldenEpubConverterI
              | ITextImageSplit
              | ITGKCard1
              | ITGKCard2
              | ITGKDoilyCard
              | ITGKAccordion
              | ITGKGridIcons
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  style?: {
    gap?: string | null;
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
    alignY?: ('start' | 'center' | 'end' | 'stretch') | null;
    flexDirection?: string | null;
    flexWrap?: string | null;
    overflow?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'flexboxLayout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IGoogleMapFooter".
 */
export interface IGoogleMapFooter {
  logo?: IImageField;
  list?:
    | {
        header?: string | null;
        horizontal?: boolean | null;
        links?:
          | {
              link?: IButton;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  locations?:
    | {
        richText?: IRichTextField;
        iframe?: string | null;
        id?: string | null;
      }[]
    | null;
  style?: {
    background?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'googleMapFooter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IGradientBG".
 */
export interface IGradientBG {
  richText?: IRichTextField;
  style?: {
    background?: string | null;
  };
  mouseColor?: string | null;
  gradientList?:
    | {
        color?: string | null;
        height?: string | null;
        width?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gradientBG';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IMediumHero".
 */
export interface IMediumHero {
  image?: IImageField;
  richText?: IRichTextField;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediumHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ICalistoLanding".
 */
export interface ICalistoLanding {
  image?: IImageField;
  richText?: IRichTextField;
  id?: string | null;
  blockName?: string | null;
  blockType: 'calistoLanding';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IScrollGrowLanding".
 */
export interface IScrollGrowLanding {
  initImg?: IImageField;
  finalImg?: IImageField;
  richText?: IRichTextField;
  style?: {
    background?: string | null;
    height?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'scrollGrowLanding';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IHeroCutout".
 */
export interface IHeroCutout {
  image?: IImageField;
  richText?: IRichTextField;
  form: number | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroCutout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IBlockColumnLayout".
 */
export interface IBlockColumnLayout {
  layout?: ('oneColumn' | 'twoOneThird' | 'oneTwoThird' | 'halfAndHalf' | 'threeColumns') | null;
  itemHeight?: string | null;
  columnOne?:
    | (
        | ITextUnderCard
        | ISingleCard
        | IAccordion
        | IHoverCard
        | IRichTextCard
        | ICutoutCard
        | IButtonBlock
        | IRichText
        | IImage
        | IStickyContainers
        | BentoGrid
        | IContactFormBlock
        | ICarousel
        | IFlexItem
        | IWavyText
        | EmboldenEpubConverterI
        | ITextImageSplit
        | ITGKCard1
        | ITGKCard2
        | ITGKDoilyCard
        | ITGKAccordion
        | ITGKGridIcons
        | IFlexboxLayout
      )[]
    | null;
  columnTwo?:
    | (
        | ITextUnderCard
        | ISingleCard
        | IAccordion
        | IHoverCard
        | IRichTextCard
        | ICutoutCard
        | IButtonBlock
        | IRichText
        | IImage
        | IStickyContainers
        | BentoGrid
        | IContactFormBlock
        | ICarousel
        | IFlexItem
        | IWavyText
        | EmboldenEpubConverterI
        | ITextImageSplit
        | ITGKCard1
        | ITGKCard2
        | ITGKDoilyCard
        | ITGKAccordion
        | ITGKGridIcons
        | IFlexboxLayout
      )[]
    | null;
  columnThree?:
    | (
        | ITextUnderCard
        | ISingleCard
        | IAccordion
        | IHoverCard
        | IRichTextCard
        | ICutoutCard
        | IButtonBlock
        | IRichText
        | IImage
        | IStickyContainers
        | BentoGrid
        | IContactFormBlock
        | ICarousel
        | IFlexItem
        | IWavyText
        | EmboldenEpubConverterI
        | ITextImageSplit
        | ITGKCard1
        | ITGKCard2
        | ITGKDoilyCard
        | ITGKAccordion
        | ITGKGridIcons
        | IFlexboxLayout
      )[]
    | null;
  bgImage?: IImageField;
  style?: {
    container?: boolean | null;
    height?: string | null;
    minHeight?: string | null;
    overflow?: string | null;
    padding?: string | null;
    color?: string | null;
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
    alignY?: ('start' | 'center' | 'end' | 'stretch') | null;
    gap?: string | null;
    borderRadius?: string | null;
  };
  mobileStyle?: {
    padding?: string | null;
    gap?: string | null;
    flexDirection?: string | null;
  };
  animation?: IAnimation;
  stickerList?:
    | {
        s?: IStickerField;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blockColumnLayout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IAnimation".
 */
export interface IAnimation {
  type?: ('viewport' | 'scroll') | null;
  /**
   * Animations that trigger when they enter the page
   */
  viewport?:
    | ('slideFadeFast' | 'slideFadeSlow' | 'slideLetters' | 'bubbleLetters' | 'drawSVG' | 'slideUpFadeIn')[]
    | null;
  /**
   * Stagger animations as they enter
   */
  stagger?: boolean | null;
  /**
   * Only play animations on enter
   */
  onlyEnter?: boolean | null;
  /**
   * How much of the element must be viewable before starting animation? 0-1
   */
  amount?: string | null;
  /**
   * Animations that play as you scroll
   */
  scroll?:
    | ('custom' | 'scale' | 'fadeIn' | 'translateUp' | 'translateDown' | 'drawSVG' | 'lineFlip' | 'fadeInEachWord')[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ITGKLandingHome".
 */
export interface ITGKLandingHome {
  imgLeft?: IImageField;
  imgRight?: IImageField;
  richText?: IRichTextField;
  flip?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tgkLandingHome';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IGutter".
 */
export interface IGutter {
  size?: ('small' | 'default' | 'medium' | 'large' | 'extraLarge') | null;
  divider: 'none' | 'center' | 'above' | 'below';
  bgColor?: {
    value?: string | null;
    onlyInContainer?: boolean | null;
  };
  bgImage?: IImageField;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gutter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IGutterV2".
 */
export interface IGutterV2 {
  style?: {
    height?: string | null;
    background?: string | null;
    color?: string | null;
    container?: boolean | null;
  };
  image?: IImageField;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gutterv2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IClipGutter".
 */
export interface IClipGutter {
  svg?: {
    clipPath?: string | null;
    viewbox?: string | null;
    background?: string | null;
  };
  style?: {
    background?: string | null;
  };
  bgImage?: IImageField;
  id?: string | null;
  blockName?: string | null;
  blockType: 'clipGutter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ICalistoFeatureCard".
 */
export interface ICalistoFeatureCard {
  cards?:
    | {
        richText?: IRichTextField;
        icon?: IIcon;
        id?: string | null;
      }[]
    | null;
  style?: {
    padding?: string | null;
    minHeight?: string | null;
    background?: string | null;
  };
  animation?: IAnimation;
  id?: string | null;
  blockName?: string | null;
  blockType: 'calistoFeatureCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IDiscountCard".
 */
export interface IDiscountCard {
  cards?:
    | {
        richText?: IRichTextField;
        includeDiscount?: boolean | null;
        price?: number | null;
        yearlyDiscount?: number | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'discountCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IMarquee".
 */
export interface IMarquee {
  items?:
    | {
        text?: string | null;
        image?: IImageField;
        id?: string | null;
      }[]
    | null;
  link?: (number | null) | Page;
  options?: {
    maskEdges?: boolean | null;
    duration?: string | null;
  };
  style?: {
    gap?: string | null;
    font?: string | null;
    color?: string | null;
    background?: string | null;
    height?: string | null;
    padding?: string | null;
    border?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'marquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ISEO".
 */
export interface ISEO {
  /**
   * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
   */
  image?: (number | null) | Asset;
  description?: string | null;
  title?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IPillRTBlock".
 */
export interface IPillRTBlock {
  image: number | Asset;
  vertAlign?: string | null;
  width?: string | null;
  height?: string | null;
  phone?: {
    width?: string | null;
    height?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'pill';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IImageRTBlock".
 */
export interface IImageRTBlock {
  link?: IButton;
  style?: {
    margin?: string | null;
    padding?: string | null;
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
    alignY?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'buttonRT';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ISVGText".
 */
export interface ISVGText {
  text?: string | null;
  shouldAnimate?: boolean | null;
  style?: {
    color?: string | null;
  };
  image?: IImageField;
  id?: string | null;
  blockName?: string | null;
  blockType: 'svgText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ILexicalMarkerIcon".
 */
export interface ILexicalMarkerIcon {
  icon?: IIcon;
  id?: string | null;
  blockName?: string | null;
  blockType: 'listMarkerIcon';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IDivider".
 */
export interface IDivider {
  style?: {
    height?: string | null;
    width?: string | null;
    border?: string | null;
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
    padding?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'divider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IRTIcon".
 */
export interface IRTIcon {
  icon?: IIcon;
  style?: {
    padding?: string | null;
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
    alignY?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'lexIcon';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ILexicalImage".
 */
export interface ILexicalImage {
  image?: (number | null) | Asset;
  alt?: string | null;
  style?: {
    padding?: string | null;
    width?: string | null;
    height?: string | null;
    alignX?: ('start' | 'center' | 'end' | 'space-around' | 'space-evenly') | null;
    alignY?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'lexImg';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IGoogleMaps".
 */
export interface IGoogleMaps {
  iframe?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'googlemaps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('super-admin' | 'user')[] | null;
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('tenant-admin' | 'tenant-viewer')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'assets';
        value: number | Asset;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        placeholder?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        sm?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        md?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        lg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xl?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  'tenant-domain'?: T;
  hero?: T | {};
  layout?: T | {};
  meta?: T | ISEOSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ISEO_select".
 */
export interface ISEOSelect<T extends boolean = true> {
  image?: T;
  description?: T;
  title?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  pages?: T;
  nav?: T | INavigationSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "INavigation_select".
 */
export interface INavigationSelect<T extends boolean = true> {
  header?: T | {};
  footer?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}